### ISSUE TITLE
Confusing output when scanning multiple K8s manifests by folder

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#238] opened 2022-12-14 19:43 UTC
**Describe the bug**
When you provide cnspec with a directory to scan for manifests the output is not entirely clear.

```
 ~/dev  cnspec scan k8s lunalectric/
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
→ discovery option auto is used. This will detect the assets: cluster, jobs, cronjobs, pods, statefulsets, deployments, replicasets, daemonsets
→ resolved assets resolved-assets=5
→ connecting to asset K8s Manifest lunalectric (code)

███████████████████████████████████████████████████████████████████████████ 100% K8s Manifest lunalectric
→ connecting to asset luna/postgres (k8s-object)

███████████████████████████████████████████████████████████████████████████ 100% luna/postgres
→ connecting to asset luna/luna-frontend (k8s-object)

███████████████████████████████████████████████████████████████████████████ 100% luna/luna-frontend
→ connecting to asset luna/postgres (k8s-object)

███████████████████████████████████████████████████████████████████████████ 100% luna/postgres
→ connecting to asset luna/luna-frontend (k8s-object)

███████████████████████████████████████████████████████████████████████████ 100% luna/luna-frontend
```

The start of the scan states `K8s Manifest lunalectric` when there is no actual manifest named lunalectric. lunalectric is the directory of manifests. We then proceed to provide a progress bar for this fictitious manifests which is confusing.

**Comment by czunker** [comment] 2023-01-04 16:55
Would this be helpful?

```
→ resolved assets resolved-assets=2
→ connecting to asset K8s Manifest directory lunalectric (code)

███████████████████████████████████████████████████████████████████████████ 100% K8s Manifest directory lunalectric
→ connecting to asset luna/postgres (k8s-object)

███████████████████████████████████████████████████████████████████████████ 100% luna/postgres


Asset: K8s Manifest directory lunalectric
```

**Comment by chris-rock** [comment] 2023-01-04 16:58
There two issues here:
1. Just having one progress bar
2. Be more specific on the root object. I think it is definitely an improvement to call it "K8S Manifest directory"

**Comment by tas50** [comment] 2023-01-04 17:33
We have an opportunity to solve the progress bar problem, which is in the works

**Comment by chris-rock** [comment] 2023-01-05 19:58
I close this issue since it not a bug and its work is not tracked here.

**Closed by chris-rock** 2023-01-05 19:58 UTC
