### ISSUE TITLE
Make compliance control output silent by default when running cnspec scan

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnspec#878] opened 2023-10-23 19:10 UTC
**Describe the bug**
When a user runs `cnspec scan <target>` compliance control data is returned without a way to turn that information off. This should be off by default with a flag to return results if desired

![image](https://github.com/mondoohq/cnspec/assets/49754039/31c1080f-a739-4f80-864c-5ce4299f6a67)

**Comment by tas50** [comment] 2024-09-10 18:32
Dupe of https://github.com/mondoohq/cnspec/issues/1378

**Closed by tas50** 2024-09-10 18:32 UTC
